DROP TYPE IF EXISTS type_name;
CREATE TYPE type_names AS ENUM (
    'Hybrid Tea',
    'Pernetiana',
    'Floribunda',
    'Grandiflora',
    'Miniature',
    'Climbing',
    'English',
    'Canadian Hardy',
    'Alba',
    'Gallica',
    'Damask',
    'Centifolia',
    'Moss',
    'Portland',
    'China',
    'Tea',
    'Bourbon',
    'Noisette',
    'Hybrid perpetual',
    'Hybrid rugosa',
    'Not Listed'
);

DROP TYPE IF EXISTS color_names;
CREATE TYPE color_names AS ENUM (
    'Apricot',
    'Orange',
    'Multi-Color',
    'Pink',
    'Purple',
    'Red',
    'White',
    'Yellow'
);

CREATE TABLE rose_gardn_roses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES rose_gardn_users(id) ON DELETE CASCADE NOT NULL,
    photo TEXT,
    name TEXT NOT NULL,
    type_name type_names,
    color color_names,
    date TIMESTAMPTZ DEFAULT now() NOT NULL
);